### ISSUE TITLE
Too many features in the starter kit

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#105]
I was thinking of this problem a bit.

On one side we would like to have as many features packt into this kit. On the other side, it will quickly get too complex for someone who wants to get started.

I see a few possible solutions, all with advantages and disadvantages:

- Have a balanced kit and maybe have this features in separate branches.
-- 'pro' easy to pick what you need out of separate branches
-- 'con' hard to maintain all separate branches and hard to combine what you really need

- Write some docs on how to integrate this.
-- 'pro' read about how to do what you need and do it your self
-- 'con' hard to write and maintain all docs

- Have two separate starter kits. Bare minimum one and full featured one with everything. Could be just a separate branch
-- 'pro' easy for someone too get started with bear minimum one and then pick what you would need out of the full featured one
-- 'con' hard to maintain two separate kits, with a lot off same code on both

**Comment by josephdburdick** [comment]
Thought: Perhaps a baseline starter kit and then branches that stay in sync with master but add features on demand?

**Comment by mitjade** [comment]
One other considiration. Let' say you started several projects out of this kit. It is hard to keep them all up to date, when you get a lot of conflicts between yor added code and new features added to the kit.
I guess this is a 'pro' for bare minimum option.

**Comment by mitjade** [comment]
I think there a 4 categories:
- can not run without (webpack, express, apollo, ...)
- can be configured as on /off (ssr, persisted queries, ...)
- optional and needs deeper integration (router, bootstrap, authentication, ...)
- examples (counter, post, ...)

For sure first is a must an last can be (fully decoupled, separate banch), the rest depends ...

**Comment by vlasenko** [comment]
Ideally I would like to have decoupled build system from examples code, where the user can update the build system from GitHub and have the option to generate scaffolding code for examples with user choices, maybe utilize [Yeoman generator](https://github.com/yeoman/generator) for scaffolding?

**Comment by swhamilton** [comment]
Agree with @mitjade as to the categories. I would say decoupled here makes the most sense:

1. Keep the boilerplate lean/modular as much as possible. Because all boilerplates get frozen as soon as you fork one, I really think this should be top priority. Keep the update pain minimal.
2. Don't maintain two repos (basic+fully configured) as that is too much work and one will get left in the dust.
3. Default to the boilterplate already having basic example of the parts (you do this already, love it as it's easy to delete the example and start fresh. maybe have a script that even removes the example like `yarn example:remove` or similar feature)
4. Provide bare-minimum snippets in the docs that show how to implement different parts (routes, bootstrap/material-ui, authentication).

I am willing to offer the authentication snippets once @GiladShoham and I throw something together. I will also be using material-ui, so I could give snippets about that too.

Let me know if you like that direction or if you'd like to see something different.

**Comment by vlasenko** [comment]
Thank you for your comments @swhamilton. I agree both with you and @mitjade and would love to see and help with your contributions both to authentication and material-ui support. I know that destiny of most boilerplates is get frozen after fork, this something I would like to change, because this boilerplate get improved actively, the topic is very new and actively changing, on top of that we are doing some experimental tweaks to Webpack to keep users of this boilerplate productive. It would be the best to have various means to upgrade after fork, parts of boilerplate, as easy as possible. Of course, we should make this boilerplate modular, but it will not be enough. Ideas are welcome.

**Comment by vlasenko** [comment]
@mitjade Should we close this issue for now? I think modules introduced by https://github.com/sysgears/apollo-fullstack-starter-kit/commit/9bf0161e91bf999c072e64e4a9f9977bf454df9f
is the way to go for now to pack much more examples into this kit and yet it is easy to strip them out.

**Comment by mitjade** [comment]
Agreed!
