### ISSUE TITLE
Apollo subscriptions

### ISSUE THREAD

**Issue by kachkaev** [sysgears/apollo-fullstack-starter-kit#4]
Привіт guys :–)

Just wondering if you're planning to add a sample [Apollo subscription](https://medium.com/apollo-stack/graphql-subscriptions-in-apollo-client-9a2457f015fb) to the counter. Real-time updates is smth that most starter kits are still missing these days; yours could one of the first ones!

Nice choice of tools BTW!

**Comment by vlasenko** [comment]
Привіт :–)

I'm worrying that this will increase starter kit size. We would like to keep it minimal, covering only tricky, but needed nuisances for productive coding, so that people don't have to throw away much code to start doing their apps. Do you think everyone will use Apollo subscriptions in their applications?

**Comment by kachkaev** [comment]
I believe that a good proportion of applications may use subscriptions in a number of places (feeds, comments, votes, etc.). A counter in your demo is a very good example of where it could be useful.

**Comment by vlasenko** [comment]
Okay, I'm sold. We will add them during next few days. :)

**Comment by vlasenko** [comment]
Here you go! Now the counter is updated in real-time using Apollo subscription.
