### ISSUE TITLE
Help - problems with routes with url params

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#83]
Hi,

I have a problem with routes with URL params like /users/:id/
The problem starts on this commit:
9c3ed91c566484989c6ab062d5de96b5c7bfda2b
It looks like it tries to find the vendor/bundle files in the wrong place.
for example, in a route with URL param (/recover/:id), the bundle will be under recover
![image](https://cloud.githubusercontent.com/assets/3840769/24101421/f1faed22-0d80-11e7-94e8-75eb2b95dbeb.png)
while on a route without an URL param it will look like this:
![image](https://cloud.githubusercontent.com/assets/3840769/24101492/369359ec-0d81-11e7-9019-28819e1a5b67.png)
you can also see that the content is different, which prevent it from work.

I'm pretty sure it's something about moving the output to the root folder, (it worked before).
But I couldn't make it work.

I'm using the starter kit on a version before the react router 4 and webpack 2.
Those may solve the problem, but I don't have the time for this upgrades now.

Any Idea about what can make this working again?

Thanks a lot.

**Comment by vlasenko** [comment]
Hi @GiladShoham,

I bet you have this issue:
https://github.com/sysgears/apollo-fullstack-starter-kit/issues/59
which have been fixed already. The idea of the fix is that vendor/bundle files and all the assets need to be referenced by absolute URLs, not relative URLs as they were used to be referenced.
So instead of this:
```
<script src={`${assetMap['bundle.js']}`} charSet="utf-8" />
```
there should be this in `html.jsx`:
<script src={`/${assetMap['bundle.js']}`} charSet="utf-8" />
Note, the leading `/` in the fixed version.

The full commit that does these replacements is here:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/2688fcb0c65f91fa4a8694efe17271ae6d9e94ea

**Comment by GiladShoham** [comment]
@vlasenko 
By the way, why didn't you merged 6f6e90f34f6ba3a2ed4852aab0284eeb2a27de96  into master?

**Comment by vlasenko** [comment]
@GiladShoham 
I have merged it:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/2688fcb0c65f91fa4a8694efe17271ae6d9e94ea

**Comment by GiladShoham** [comment]
I see now.
It's the same diff but it's not a merge, that's what confused me.

![image](https://cloud.githubusercontent.com/assets/3840769/24102998/7617088e-0d86-11e7-91ff-ec56723150a0.png)

**Comment by vlasenko** [comment]
Yes, I have cherry picked this commit from non-master branch, since I did the fix in that branch first and the cherry-picked commit to master.
